package com.github.jbescos.gameplay.roguelite;

public enum RogueliteCardId {
    CLUB_TUNE,
    SPORT_TUNE,
    AERO_TRIM,
    SHORT_GEARING,
    RACE_TUNE,
    HEAVYWEIGHT_TUNE,
    LOW_DRAG_BODY,
    DRIFT_DIFFERENTIAL,
    CHAMPIONSHIP_TUNE,
    GROUND_EFFECT,
    VELOCITY_SHELL,
    TORQUE_VECTORING,

    CORNER_EXIT,
    DRAFT_HUNTER,
    CLEAN_MOMENTUM,
    RECOVERY_LAUNCH,
    DRIFT_SLINGSHOT,
    SLIPSTREAM_SLINGSHOT,
    OVERTAKE_SURGE,
    APEX_SLINGSHOT,
    PERFECT_LAP,
    RACECRAFT_MASTERY,

    NITRO_PULSE,
    GRIP_FAN,
    RAM_REACTOR,
    DRAFT_MAGNET,
    PHASE_SHIELD,
    ROCKET_EXHAUST,
    GRAVITY_WELL,
    OVERDRIVE_COIL,
    HYPERDRIVE,
    CROWN_ENGINE
}
